import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
const roboto = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Malik Ahad Ali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased px-10 lg:px-40`}>
        {children}
      </body>
    </html>
  );
}
